steps:
  - uses: actions/checkout@v3
  - uses: jiro4989/setup-nim-action@v1
    with:
      nim-version: '1.6.12' # default is 'stable'
      repo-token: ${{ secrets.GITHUB_TOKEN }}
  - run: nimble build -d:release -Y
